### ISSUE TITLE
Unable to deploy private function with a tag on the image

### ISSUE THREAD

**Issue by BurtonR** [openfaas/faas-swarm#19]
Unable to deploy a function with an image that is in a private repository (either Docker Hub, or private) when using a tag on the image. `private-registry.com/burtonr/test-fn:0.1`

## Expected Behaviour

Deploy function successful

## Current Behaviour

The CLI returns
```
Unexpected status: 400, message: Invalid registry auth
```

The log message in `faas-swarm`:
```
Error building registry auth configuration: invalid reference format
```

This is the line that throws the error: https://github.com/openfaas/faas-swarm/blob/master/handlers/deploy.go#L194

## Possible Solution

We'd need to parse the `dockerImage` input to see if there is a tag being used. If so, call the `WithTag()`, otherwise call the current `WithName()`

Or, possibly update it to _always_ call the `WithTag()` function, by setting the tag to `latest` if it's not supplied. That way there wouldn't be 2 different code paths to follow...

## Steps to Reproduce (for bugs)

1. Create a function and update the `function.yml` `image` to use a tag: `burtonr/test-fn:0.1`
2. Push the image to a private registry, Docker Hub or private instance
3. Deploy the function to a Swarm OpenFaaS cluster
4. Observe the CLI response and `faas-swarm` logs

## Context

Unable to use versions of functions from my private registry

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.03.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm 
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 17.10 (also tested on Play-With-Docker)
* Link to your project or a code example to reproduce issue:
_it's private_ :stuck_out_tongue_winking_eye:

**Comment by alexellis** [comment]
Thanks for reporting the problem. Can we reproduce the error in a test harness / unit test?

**Comment by alexellis** [comment]
@BurtonR ^ thoughts?

**Comment by BurtonR** [comment]
I'd need to look through the code a little more closely, but yes, I believe there should be a way to get this to happen in a test case. I think we'd only need to set the `RegistryAuth` in the function deploy request to trigger the function that does the `WithName()` call which causes the issue

**Comment by JohnOllhorn** [comment]
Hello, folks,

I'm sorry, but I have to reopen the post.

I use the current version of OpenFaas together with Docker Swarm (multi Node) and a private Docker Registry.

I've read all contributions to this bug, but I still get this message:

```bash
> faas-cli deploy -f stack.yml --gateway https://DOMAIN --network proxy --readonly --send-registry-auth
```

```bash
Deploying: SERVICENAME.

Unexpected status: 400, message: Invalid registry auth

Function 'SERVICENAME' failed to deploy with status code: 400
```
I am successfully logged into my registry and OpenFaas
