### ISSUE TITLE
Function CRUD operations should return 202 accepted

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-swarm#25]
Since Swarm is effectively declarative CRUD operations should return 202 Accepted rather than 200 OK since we do not know if things are actually OK that that point. The *R* of CRUD (retrieve) can return 200 OK.

Context - Issue raised on FaaS repo by Simon @templum https://github.com/openfaas/faas/issues/693

**Comment by viveksyngh** [comment]
Yes, I will take this one.

**Comment by alexellis** [comment]
@viveksyngh this issue has been open for several months now with no updates. What do you want to do?

**Comment by viveksyngh** [comment]
I have done changes for faas-netes, I will test that. Once that is done I will work on this one.
