### ISSUE TITLE
Update the function proxy handler to use the faas-provider proxy implementation

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-swarm#38]
With the merge of openfaas/faas-provider#11 we can replace the current `FunctionProxy` implementation with the standardized proxy implementation from `faas-provider`.  This will ensure consistent proxy behavior among the official providers. 

## Possible Solution

This requires updating the `faas-provider` version that is vendored and then separating the function lookup into the `BaseURLResolver` interface defined in the `faas-provider`

**Comment by alexellis** [comment]
Released in 0.5.0 🎉 - https://github.com/openfaas/faas-swarm/releases/tag/0.5.0

**Comment by LucasRoesler** [comment]
Derek close
