### ISSUE TITLE
Tests required for faas-swarm secrets handler

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-swarm#45]
## Expected Behaviour

The secrets handler for faas-swarm should have tests. Use the `httptest` package to achieve this.

## Current Behaviour

Unavailable.

## Possible Solution

You may need to use an interface instead of the Docker client in the handler's make function so that it can be stubbed out with a test double to return the data you need in the test.

See the tests in faas-netes / openfaas-operator for an example of how this was done for other platforms.

**Comment by bartsmykla** [comment]
Derek assign: me
