### ISSUE TITLE
UpdateSecret function in secrets.go handler will not work as Docker secrets are immutable

### ISSUE THREAD

**Issue by codegold79** [openfaas/faas-swarm#65]
## Expected Behaviour

All functions in the secrets handler for Docker Swarm should work as intended if they are in the code base.

## Current Behaviour

The function updateSecret() in the secrets.go handler does not update secrests; it can't because Docker secrets are immutable. An unhelpful status 500 error is thrown when attempting to update a secret via the API gateway using `curl -d '{"name":"secret-name","value":"test-edit-i"}' -X POST http://127.0.0.1:8080/system/secrets`.

## Possible Solution

1. Remove the updateSecret() function completely
2. Handle PUT requests to update secrets with a 405 "Method not allowed" error.

## Steps to Reproduce (for bugs)

1. Remove faas-netes or other non-Docker Swarm version of OpenFaaS on local machine.
2. git clone the openfaas/faas repo
3. run `./deploy_stack.sh -n`, which installs with basic auth disabled
4. create a secret with `curl -d '{"name":"secret-name","value":"test"}' -X POST http://127.0.0.0.1:8080/system/secrets`
5. `curl -d '{"name":"secret-name","value":"test-edit-i"}' -X POST -v http://127.0.0.1:8080/system/secrets`
6. An `HTTP/1.1 500 Internal Server Error` is returned.

## Context

I'm new to Docker and I had no idea that Docker secrets were immutable. Given that, I spent a day trying to figure out why the update part of my test in https://github.com/openfaas/certifier/pull/22 was failing for Docker Swarm installation, but not for faas-netes. The error returned was a 500 error, which made me think it was some logic error on our side.

The code base in faas-swarm wasn't helpful, because the presence of updateSecret() makes it seem like updating was possible. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
N/A - I didn't use faas-cli for the secrets CRUD testing.

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker engine version is 19.03.5.

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS Catalina

* Link to your project or a code example to reproduce issue:
https://github.com/openfaas/certifier/pull/22

**Comment by viveksyngh** [comment]
I will work on this one.

**Comment by alexellis** [comment]
Thanks @viveksyngh, when should I check back for a PR?

**Comment by viveksyngh** [comment]
Added the PR.
